from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.lib import colors
from datetime import datetime
import io
from reportlab.graphics.shapes import Drawing
from reportlab.graphics.charts.doughnut import Doughnut
import requests

def funny_speed_comment(speed):
    if speed is None:
        return "We couldn't measure your speed. Your internet might be hiding."

    if speed < 5:
        return "Your internet is extremely slow. Even a turtle might outrun it."
    elif speed < 15:
        return "Your internet is jogging. Not terrible, but definitely not sprinting."
    elif speed < 50:
        return "Decent speed! Streaming should work fine."
    else:
        return "Nice! Your internet is flying."


def funny_latency_comment(latency):
    if latency is None:
        return ""
    if latency > 120:
        return "High latency detected. Online games might feel like time travel."
    elif latency > 80:
        return "Latency is a bit high. Video calls may occasionally freeze."
    else:
        return "Latency looks healthy."


def generate_pdf_report(data):
    buffer = io.BytesIO()

    report_time = datetime.now().strftime("%d %B %Y, %I:%M %p")
    doc = SimpleDocTemplate(buffer, pagesize=A4)

    styles = getSampleStyleSheet()
    elements = []

    analysis = data.get("analysis", {})
    speed = data.get("speed", {})
    latency = data.get("latency", {}).get("summary", {})
    dns = data.get("dns", {}).get("summary", {})
    packet = data.get("packet_loss", {})
    isp = get_isp()

    health_score = analysis.get("health_score", 0)
    download = speed.get("download_mbps")
    upload = speed.get("upload_mbps")
    lat = latency.get("average")

    elements.append(Paragraph("<font size=22><b>FixMyInternet Network Diagnostic Report</b></font>", styles['Title']))
    elements.append(Spacer(1,30))

    elements.append(Paragraph(f"<b>ISP:</b> {isp}", styles['Normal']))
    elements.append(Paragraph(f"<b>Generated:</b> {report_time}", styles['Normal']))

    elements.append(Spacer(1,20))

    elements.append(Paragraph(f"<b>Health Score:</b> {health_score} / 100", styles['Heading2']))
    elements.append(Spacer(1, 10))

    elements.append(Paragraph(f"<b>Diagnosis:</b> {analysis.get('diagnosis','')}", styles['Heading3']))
    elements.append(Spacer(1, 10))

    elements.append(Paragraph(analysis.get("explanation", ""), styles['BodyText']))
    elements.append(Spacer(1, 20))

    data_table = [
        ["Metric", "Result"],
        ["Download Speed", f"{download} Mbps"],
        ["Upload Speed", f"{upload} Mbps"],
        ["Latency", f"{latency.get('average')} ms"],
        ["Jitter", f"{latency.get('jitter')} ms"],
        ["DNS Average", f"{dns.get('average')} ms"],
        ["Fastest DNS", dns.get("fastest_server")],
        ["Packet Loss", f"{packet.get('packet_loss_percent')} %"]
    ]

    table = Table(data_table, colWidths=[200, 200])

    table.setStyle([
    ('BACKGROUND', (0,0),(-1,0), colors.HexColor("#2563EB")),
    ('TEXTCOLOR',(0,0),(-1,0),colors.white),

    ('FONTNAME', (0,0),(-1,0),'Helvetica-Bold'),

    ('BACKGROUND',(0,1),(-1,-1),colors.whitesmoke),

    ('GRID',(0,0),(-1,-1),0.5,colors.grey),

    ('ROWBACKGROUNDS',(0,1),(-1,-1),
        [colors.whitesmoke, colors.lightgrey])
    ])

    elements.append(table)
    elements.append(Spacer(1, 30))

    elements.append(Paragraph("<b>Network Performance Insights</b>", styles['Heading2']))
    elements.append(Spacer(1, 10))

    elements.append(Paragraph(funny_speed_comment(download), styles['BodyText']))
    elements.append(Spacer(1, 5))

    elements.append(Paragraph(funny_latency_comment(lat), styles['BodyText']))
    elements.append(Spacer(1, 20))

    elements.append(Paragraph("<b>Recommendation</b>", styles['Heading2']))
    elements.append(Spacer(1, 10))

    elements.append(Paragraph(analysis.get("recommendation", ""), styles['BodyText']))
    elements.append(Spacer(1, 30))

    elements.append(
        Paragraph(
            "Generated by FixMyInternet — helping you fix bad WiFi since today.",
            styles['Italic']
        )
    )
    doc.build(elements)

    buffer.seek(0)
    return buffer

def create_health_chart(score):
    drawing = Drawing(200, 200)

    chart = Doughnut()
    chart.x = 50
    chart.y = 50
    chart.width = 100
    chart.height = 100

    chart.data = [[score, 100 - score]]

    chart.labels = ["Health", ""]

    if score >= 80:
        chart.slices[0].fillColor = colors.green
    elif score >= 50:
        chart.slices[0].fillColor = colors.orange
    else:
        chart.slices[0].fillColor = colors.red

    chart.slices[1].fillColor = colors.lightgrey

    drawing.add(chart)
    return drawing

def get_isp():
    try:
        res = requests.get("https://ipinfo.io/json", timeout=3).json()
        isp = res.get("org", "")

        if isp.startswith("AS"):
            isp = isp.split(" ", 1)[1]
        return isp
    except:
        return "Unknown ISP"